Login test
sidharth-404/Diagramming-Tool-frontend-React pull request #10
Opened 2024-03-26 09:05 UTC by LakshmiMadhuNair

2024-03-26 11:09 UTC, AnushiyaM11 requested changes
Please do the needful changes

2024-03-26 17:36 UTC, Sharz-dev approved these changes

2024-03-28 04:05 UTC, AnushiyaM11 commented on diagramming-tool/src/Component/Login/LoginPage.jsx
> +      const response = await authApi.login(email, password);
API calls are expected to be in the services folder

2024-03-28 04:06 UTC, AnushiyaM11 commented on diagramming-tool/src/Component/Login/auth.js
You can move this file to services folder as it is API cal

2024-03-28 06:10 UTC, AnushiyaM11 approved these changes
Approved

2024-03-28 06:12 UTC, Sharz-dev approved these changes

2024-03-28 06:13 UTC, merged